server:
  port: 8081
logging:
  level:
    com.icho: debug
mybatis:
  type-aliases-package: com.icho.bean # 别名扫描
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
# mapper-locations: mybatis/mapper/*.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #数据源1
    url1: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT
    username1: root
    password1: 4321
    #数据源2
    url2: jdbc:mysql://127.0.0.1:3306/test_bak?serverTimezone=GMT
    username2: root
    password2: 4321
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /

swagger:
  production: false
  basic:
    enable: true
    username: icho
    password: 4321